# Generated by Django 3.2.8 on 2021-12-15 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('regdate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectionid', models.CharField(max_length=10, null=True)),
                ('connectiontype', models.CharField(max_length=100, null=True)),
                ('connectionstartdate', models.DateField(null=True)),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('connectionload', models.CharField(max_length=100, null=True)),
                ('plotno', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billformonth', models.CharField(max_length=50, null=True)),
                ('currentreading', models.CharField(max_length=100, null=True)),
                ('previousreading', models.CharField(max_length=100, null=True)),
                ('totalunit', models.CharField(max_length=100, null=True)),
                ('chargeperunit', models.CharField(max_length=100, null=True)),
                ('finalamount', models.CharField(max_length=100, null=True)),
                ('duedate', models.DateField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.connection')),
            ],
        ),
    ]
